### PR TITLE
Ssl handling

### LINKED ISSUE #14: Flag to turn off all certificate validation
See corresponding TS implementation of this feature. This helps during the initial setup when self-signed certificates or broken certificates are used to still allow a successful test of the agent's upload functionality

### PR DESCRIPTION
**Pull request by karottenreibe**
Fixes #14 

- [x] [No new Teamscale findings](https://build.cqse.eu/teamscale/delta.html#input/jacoco-client/?showMergeFindings=true)
- [x] [Changes are tested adequately](https://build.cqse.eu/teamscale/tests.html#/jacoco-client/)
- [x] USAGE.md updated in case of user-visible changes
- [x] CHANGELOG.md updated

### CODE REVIEW

**Comment by karottenreibe** [comment]
I'm not sure how adding the SLF4J Logger to the teamscale-client project affects the gradle plugin. I also wasn't sure how to test that

**Comment by karottenreibe** [comment]
Code is adapted from TS repository so should work :tm:

**Comment by karottenreibe** [comment]
todo for myself: test this with an invalid certificate locally

**Comment by karottenreibe** [comment]
rfr again, but no hurry on this one :-)
I tested this on my local machine and it accepted an invalid certificate

**Comment by karottenreibe** [comment]
there was a merge conflict on the default timeouts (20s on this branch, 60s on master) I left the 60s timeout as the default. Let me know if you think that's not what we want (I wasn't sure)

**Comment by DreierF** [comment]
Changes look good to me, but there are merge conflicts with master

**Comment by DreierF** [comment]
FYI GitHub has added a new button :)
image

**Comment by karottenreibe** [comment]
cool!

**Comment by karottenreibe** [comment]
tested this again on my machine against demo.teamscale.com since the merge conflicts were non-trivial. would be cool to get this merged and released soon :-)

**Pull request merged**
