### PR TITLE
Sane default logging

### LINKED ISSUE #13: Make default logging behavior more useful
Default if nothing is configured should be logging to a new dir logs/ next to the profiler jar with rolling file and info level

### PR DESCRIPTION
**Pull request by karottenreibe**
fixes #13 

- [x] [No new Teamscale findings](https://build.cqse.eu/teamscale/delta.html#input/jacoco-client/?showMergeFindings=true)
- [x] [Changes are tested adequately](https://build.cqse.eu/teamscale/tests.html#/jacoco-client/)
- [x] USAGE.md updated in case of user-visible changes
- [x] CHANGELOG.md updated
- [x] build.gradle version number increased according to semantic versioning

### CODE REVIEW

**Comment by karottenreibe** [comment]
rfr

**Comment by karottenreibe** [comment]
Had to reconfigure the TS project to look at Github ;-) Fixed the findings there

**Comment by karottenreibe** [comment]
rfr again

**Comment by DreierF** [comment]
All these changes are also contained in the other PR, right?
So can close this PR?

**Comment by karottenreibe** [comment]
good point!

**Pull request closed without merging**
